spring:
  application:
    name: learn-spring-security
  datasource:
    url: "jdbc:mysql://localhost:3306/microservice_auth"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
